name: Send Daily Love Message

on:
  schedule:
    - cron: '0 6 * * *'  # UTC time (6 AM UTC = 8 AM South Africa)
  workflow_dispatch:     # Optional: lets you trigger it manually too

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install twilio python-dotenv

      - name: Run the message script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
        run: python send_message.py
